###

POST http://localhost:9000/signup
Content-Type: application/x-www-form-urlencoded

{
    "lastname": "Chu",
    "firstname": "Kai Chun",
    "username": "Casey",
    "email": "1155093260@link.cuhk.edu.hk",
    "password": "Caseychu0617",
    "gender": "male",
}